package config

import (
	"fmt"
	"path/filepath"
	"sync"

	"github.com/BurntSushi/toml"
)

type AutoGenerated struct {
	Debug   bool   `toml:"debug"`
	Version string `toml:"Version"`
	Servers struct {
		Type      string `toml:"Type"`
		Host      string `toml:"Host"`
		Username  string `toml:"Username"`
		Password  string `toml:"Password"`
		Dbname    string `toml:"Dbname"`
		Tablename string `toml:"Tablename"`
	} `toml:"Servers"`
}

var (
	cfg  *AutoGenerated
	once sync.Once
)

func Config() *AutoGenerated {
	return cfg
}

func ReloadConfig() {
	filePath, err := filepath.Abs("config.toml")
	if err != nil {
		panic(err)
	}
	fmt.Printf("parse toml file once. filePath: %s\n", filePath)
	config := new(AutoGenerated)
	if _, err := toml.DecodeFile(filePath, config); err != nil {
		panic(err)
	}
	cfg = config
}


