RunMode ="debug"

#版本号
Version="1.0"

[app]
PAGE_SIZE = 10
JWT_SECRET = '23347$040412'

[server]
HTTP_PORT = 8080
READ_TIMEOUT = 60
WRITE_TIMEOUT = 60


#数据库
[database]
Type = "mysql"
#127.0.0.1:3306
Host = "127.0.0.1:3306"
Username = "root"
Password = ""
Dbname = "blog"
Tablename = "blog_"

